// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLlGRAPGLbuj-aAErNvzJXoIJGMDgLlo',
    appId: '1:645214741363:web:612ffdfd1d38faf9919b06',
    messagingSenderId: '645214741363',
    projectId: 'chatapp-46955',
    authDomain: 'chatapp-46955.firebaseapp.com',
    storageBucket: 'chatapp-46955.appspot.com',
    measurementId: 'G-Z3L6789QCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5_GutNnVsDBbrce5XuX22VbqMHqLvOs',
    appId: '1:645214741363:android:6674db730ab9ef82919b06',
    messagingSenderId: '645214741363',
    projectId: 'chatapp-46955',
    storageBucket: 'chatapp-46955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9WqMhHIQKA6K20opXupl46jszjGz39us',
    appId: '1:645214741363:ios:de25419860ea5c0f919b06',
    messagingSenderId: '645214741363',
    projectId: 'chatapp-46955',
    storageBucket: 'chatapp-46955.appspot.com',
    iosBundleId: 'com.example.chatifyClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqLlGRAPGLbuj-aAErNvzJXoIJGMDgLlo',
    appId: '1:645214741363:web:2a091aa9c4a717b4919b06',
    messagingSenderId: '645214741363',
    projectId: 'chatapp-46955',
    authDomain: 'chatapp-46955.firebaseapp.com',
    storageBucket: 'chatapp-46955.appspot.com',
    measurementId: 'G-290HWSFZQS',
  );
}
